import { currentTask, isArchivedStub, byRecency } from "./model.mjs";

const MARK = { todo: "[ ]", in_progress: "[~]", done: "[x]", blocked: "[!]" };

function taskLine(t) {
  const bits = [`- ${MARK[t.status] ?? "[ ]"} \`${t.id}\` ${t.name} (${t.status}`];
  let line = bits[0];
  if (t.status === "blocked" && t.waiting_on) line += ` — waiting on: ${t.waiting_on}`;
  line += ")";
  if (t.status === "done" && t.result) line += ` — ${t.result}`;
  return line;
}

/** Deterministic snapshot — same state in, byte-identical markdown out. */
export function renderMarkdown(state, config) {
  const lines = [];
  lines.push("<!-- generated by goalpost — do not hand-edit; run `goalpost generate` -->");
  lines.push("# Roadmap");
  lines.push("");

  const cur = currentTask(state);
  if (cur) {
    lines.push(`**Now:** \`${cur.id}\` ${cur.name} (${cur.status})`);
    for (const c of cur.success_criteria ?? []) lines.push(`  - goal: ${c}`);
    for (const v of cur.verification ?? []) lines.push(`  - exit: \`${v}\``);
  } else {
    lines.push("**Now:** nothing pointed — `goalpost claim` to pick up the next task");
  }
  lines.push("");

  const milestones = state.milestones ?? [];
  const grouped = new Set();
  for (const m of milestones) {
    const tasks = state.tasks.filter((t) => t.milestone === m.id);
    if (tasks.length === 0) continue;
    lines.push(`## ${m.name}`);
    lines.push("");
    for (const t of tasks) {
      lines.push(taskLine(t));
      grouped.add(t.id);
    }
    lines.push("");
  }

  const ungrouped = state.tasks.filter((t) => !grouped.has(t.id) && !isArchivedStub(t));
  if (ungrouped.length > 0) {
    if (milestones.length > 0) lines.push("## Tasks");
    if (milestones.length > 0) lines.push("");
    for (const t of ungrouped) lines.push(taskLine(t));
    lines.push("");
  }

  const stubs = state.tasks.filter((t) => isArchivedStub(t));
  if (stubs.length > 0) {
    lines.push(`## Archived (${stubs.length})`);
    lines.push("");
    for (const t of byRecency(stubs)) lines.push(`- [x] \`${t.id}\` ${t.name} (archived)`);
    lines.push("");
  }

  return lines.join("\n") + "\n";
}
